version: 2

models:
  - name: dim_geo
    description: "List of unique geo locations"
    columns:
      - name: geoid
        data_type: string
        description: ""

      - name: iso_code
        data_type: string
        description: ""

      - name: continent
        data_type: string
        description: ""

      - name: location
        data_type: string
        description: ""

  - name: fact_covid_cases
    description: "Covid cases details over continets and years"
    columns:
      - name: continent
        data_type: string
        description: ""

      - name: location
        data_type: string
        description: ""

      - name: mon_year
        data_type: string
        description: ""

      - name: population_density
        data_type: float64
        description: ""

      - name: median_age
        data_type: float64
        description: ""

      - name: total_male_smokers
        data_type: float64
        description: ""

      - name: total_female_smokers
        data_type: float64
        description: ""

      - name: total_new_cases
        data_type: float64
        description: ""

      - name: total_cases
        data_type: float64
        description: ""

      - name: total_new_deaths
        data_type: float64
        description: ""

      - name: total_deaths
        data_type: float64
        description: ""

      - name: total_icu_patients
        data_type: float64
        description: ""

      - name: total_hosp_patients
        data_type: float64
        description: ""

      - name: total_weekly_hosp_admissions
        data_type: float64
        description: ""

      - name: total_weekly_icu_admissions
        data_type: float64
        description: ""

      - name: total_new_tests
        data_type: float64
        description: ""

      - name: total_tests
        data_type: float64
        description: ""

      - name: total_new_vaccinations
        data_type: float64
        description: ""

      - name: total_vaccinations
        data_type: float64
        description: ""

      - name: people_fully_vaccinated
        data_type: float64
        description: ""

      - name: people_vaccinated
        data_type: float64
        description: ""

      - name: total_boosters
        data_type: float64
        description: ""

      - name: stringency_index
        data_type: float64
        description: ""